### ISSUE TITLE
Move all group permissions to localgov_microsites_permissions module

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites_group#105]
Group permissions need some unpicking because they are creating dependencies across everything.

At a minimum we should move the permissions config files to the localgov_microsites_permissions module, but maybe we want to implement something like what we're doing with `hook_localgov_roles_default`

Thoughts @ekes @finnlewis ?

**Comment by finnlewis** [comment]
I'm not clear how putting all permissions in a separate module helps. Could we discuss this at some point or clarify @stephen-cox @ekes ?

**Comment by stephen-cox** [comment]
@finnlewis @ekes Rather than moving permissions to localgov_microsites_permissions (which I think can be removed), I propose adding a RolesHelper class like (https://github.com/localgovdrupal/localgov_core/blob/2.x/modules/localgov_roles/src/RolesHelper.php) and using this to decouple the dependency between localgov_microsites_group and any modules that need to define permissions.

PR with the proposal following shortly.
