### ISSUE TITLE
Redirect users from group content entities to the content

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#107]
Once we've sorted the GroupContent question (https://github.com/localgovdrupal/localgov_microsites_group/issues/23)

We'll probably need to hide access to the group content entity and redirect users from said entity to the actual content, just in case!

**Comment by ekes** [comment]
PR https://github.com/localgovdrupal/localgov_microsites_group/pull/129

**Comment by ekes** [comment]
Moved to done. Closing.
