### ISSUE TITLE
Add venues to microsites directories

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#108]
From: https://github.com/localgovdrupal/localgov_microsites_group/pull/106

Directory venues aren't enabled by default because the Drupal site install hangs indefinitely when trying to enable something to do with this. It is possible to enable venues after a site install, so I suspect some sort of run condition, but haven't spent much time investigating this yet.

## User story

As a microsite admin
I want to add a directory entry with location to my microsite directory
So that I can display the school location

## Notes

Maybe this is an opportunity to add a new directory entry type that is NOT called 'venue'. Place? Location? ...

**Comment by stephen-cox** [comment]
PR to fix the issue with directories with further discussion here https://github.com/localgovdrupal/localgov_directories/pull/202
