### ISSUE TITLE
Add a location entity to a directory entry (in a microsite)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#109]
From https://github.com/localgovdrupal/localgov_microsites_group/pull/106

When venues are enabled it's not possible to add addresses as anyone other than User 1. I expect something like https://github.com/localgovdrupal/localgov_microsites/issues/111 is going on.

We think this might be an issue for media, etc. or anything that is created and referenced in an inline form .

Might want to generalise this approach: 
https://github.com/localgovdrupal/localgov_microsites/pull/113/files

**Comment by stephen-cox** [comment]
Turns out this was just a permissions issue. Should be fixed with https://github.com/localgovdrupal/localgov_microsites_group/pull/134/commits/1cfdc1a3a46e6c721d42409c94c43da9e7b8772c
