### ISSUE TITLE
Microsites listing page, show more information about microsite (join group domain config to group for view)

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#12]
Can we add a relation so that group domain config can be pulled up in the group base view. For /admin/microsites would add the ability to add the URL or Homepage for example.

**Comment by willguv** [comment]
@msayoung any idea what this is? Thanks

**Comment by finnlewis** [comment]
Closing as we don't think this is needed. Feel free to re-open @ekes if you feel differently.
