### ISSUE TITLE
On admin pages, "skip to main" link jumps past the admin tabs.

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#131]
The "skip to main" link doesn't work on the Group page. 

To replicate: use the tab key to tab to the Skip to main link, hit enter. 
Expected result: focus jumps to the main content area

On the NODES tab: /group/1/nodes 

The Skip to main does work, but skips content that should be contained in the `main`

**Comment by willguv** [comment]
@msayoung is this still an issue?

**Comment by msayoung** [comment]
The original issue is fixed, but I've updated the issue. I suggest that the admin tabs _should_ be in the <main> 



![Image](https://user-images.githubusercontent.com/3852805/192535742-1c54c243-a352-41f9-96a0-6e344b94b3bd.png)

**Comment by msayoung** [comment]
this is how things work in claro, i'm going to close this and reopen there if we feel strongly about it, which I'm not sure I do.
