### ISSUE TITLE
Managing vocabularies and taxonomy terms in a group

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites_group#136]
Current plan is for vocabularies to be shared across groups and taxonomy terms to be group content.

We will need to implement a UI for this. One's been built for managing directory facets, so something similar can be done for this.

**Comment by stephen-cox** [comment]
@ekes This will be required for both news and events content types, so have created a separate issue for it.

Is there anything else we need to consider here?

**Comment by ekes** [comment]
Don't know if we want to look at https://www.drupal.org/project/group_taxonomy

I'm pretty sure we don't want to use the patch that would add vocabulary (see issue about config entities elsewhere); but maybe it's better to use it for the terms? Or maybe it's better doing it ourselves the same?

**Comment by ekes** [comment]
My other probable requirement is we will want to differentiate between vocabularies:- I can see the use case where Open Active vocabulary or such has been imported and is fixed, so that vocabulary has terms shared between all sites that can't be edited; where as another can.

**Comment by ekes** [comment]
Oh.

https://www.drupal.org/project/group_term

**Comment by stephen-cox** [comment]
I had a look at both those.

I don't think we want [Group Taxonomy](https://www.drupal.org/project/group_taxonomy) as we need that patch. At the moment people seem okay with shared vocabs and group terms.

[Group Term](https://www.drupal.org/project/group_term) will make it easier to create group content plugins as we won't need to write our our plugin classes for each vocab, but that it pretty much all it provides. We would still need to create a UI for managing group terms. One option would be to pacth/fork the module to add a UI. Only concerns with Group Term is it alpha without much dev and only used on 55 sites.

**Comment by ekes** [comment]
Had a look now. Three commits. I'm guessing because it is really just the enabler, view, tokens and permissions. Most of which seems c&p code.

But if I'm right it is breaking up the permissions per bundle and the ContentEntabler, which is good.

So if I read it correctly we could use that, save us doing the same c&p. If there are issues down the line that are a problem we can fork - or ask for maintainership?

Then make a localgov_microsites_group_term_ui that adds the UI for managing the terms? Rather than try and get it into group_term?

**Comment by stephen-cox** [comment]
Sounds like a plan. Thoughts on whether localgov_microsites_group_term_ui module should be standalone rather than a submodule of localgov_microsites_group? I lean towards a standalone module, but it's going to be quite simple so could just go into localgov_microsites_group.

**Comment by ekes** [comment]
For standalone: It probably could operate completely independently of microsites, so be useful for re-use. [update:] at which point it becomes group_term_ui module :)
For submodule: Everything else is, like the facets code doing the same, so that's easy.

No strong opinion either way really.

**Comment by finnlewis** [comment]
While testing news, with taxonomy term topcs (categories) we  try to select a term on a news article and get: 
`
 This entity (taxonomy_term: 3) cannot be referenced. `
