### ISSUE TITLE
Blocks displayed on events listing pages even when it's a 404 page

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites_group#139]
From #138 and https://github.com/localgovdrupal/localgov_microsites/issues/119

The LocalGov Events module provides an events view at /events. By default this will be displayed on all sites, even if they're not using events.

The Microsites Events module checks if there are any events and if not shows a 404; https://github.com/localgovdrupal/localgov_microsites_group/blob/bcb7e9975b6a3de231e30541b8de9cd4ac7bb0cd/modules/localgov_microsites_events/src/EventSubscriber/EventsListingCheckEventSubscriber.php#L85-L88

The problem with this approach is blocks are displayed on 404 pages which is strange. See screenshot.

![image](https://user-images.githubusercontent.com/7189914/178525538-18c41405-8456-4390-8765-8bb77c221bed.png)

The obvious solution is to hide sidebars on error pages in the theme. Are there any situation where we might want to display sidebars on error pages? Are there any better ways to hide blocks on 404 error pages?

Any thoughts on this? @ekes @finnlewis @markconroy

**Comment by markconroy** [comment]
We could create a `page--status.html.twig` (or some other name), and let page--404.html.twig, page--403.html.twig, etc use it, and have that page template not have any sidebar regions in it.

**Comment by finnlewis** [comment]
That might be good for other reasons too, just to have a bit more control over the presentation / layout of error pages.

**Comment by markconroy** [comment]
Should we apply this fix in localgov_base or in localgov_microsites_base?

**Comment by finnlewis** [comment]
Better upstream in localgov_base ?

**Comment by finnlewis** [comment]
@markconroy passing this to you as it sounds like you might be best placed to address this in the theme. Feel free to discuss and pass it around if I've got the wrong end of the stick!

**Comment by markconroy** [comment]
I'm working on this (in localgov_base) but on a microsite I am not getting a 404 if there are no events. I'm getting the general "no events listed" message.
![Screenshot 2022-07-25 at 10 51 24](https://user-images.githubusercontent.com/2183332/180749874-90447277-302f-46f8-bbd1-5d4a342eb14a.jpg)

**Comment by markconroy** [comment]
PR: https://github.com/localgovdrupal/localgov_base/pull/252

**Comment by markconroy** [comment]
I think this can be closed now after https://github.com/localgovdrupal/localgov_base/pull/252 got merged.
