### ISSUE TITLE
Create Microsites Wizard: Configurable domain group settings.

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#15]
[For sprint 5+]

Which plugin, and fields are show on the domain settings are hard coded, could be made configurable.

As part of the wizard form, we want to be able to offer some further configuration options to allow the microsites controller to decide: 
 - which content types are available
 - what permissions are being deployed

**Comment by ekes** [comment]
Related #20

**Comment by willguv** [comment]
@ekes @finnlewis are we doing a wizard now? Feels like this card can go
