### ISSUE TITLE
Add PHPunit (functional) tests for microsites creation wizard

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#18]
Need to step through the form every which way - with different group type settings for membership.

**Comment by willguv** [comment]
@ekes @finnlewis has some of this been covered already?

**Comment by finnlewis** [comment]
See https://github.com/localgovdrupal/localgov_microsites_group/pull/226 and https://github.com/localgovdrupal/localgov_microsites_group/issues/225
