### ISSUE TITLE
Autocomplete field widgets don't work with group taxonomy terms

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites_group#180]

**Comment by stephen-cox** [comment]
This problem is caused because when filtering terms with the autocomplete widget an entity query is used and the Group module alters this is a way that breaks for taxonomy terms. I've tracked the issue down to something in [Drupal\group\QueryAccessEntityQueryAlter::doAlter()](https://git.drupalcode.org/project/group/-/blob/8.x-1.x/src/QueryAccess/EntityQueryAlter.php#L164)

**Comment by ekes** [comment]
`domain_group` also implements that alter.

**Comment by stephen-cox** [comment]
I've found the issue: https://www.drupal.org/project/group_term/issues/3302669

Just need to create a patch on the Group Term module.

**Comment by stephen-cox** [comment]
Turns out the fix was already in the dev branch :roll_eyes:
