### ISSUE TITLE
Create Microsite "editor" role for group / microsite members

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#190]
As a microsite editor X 
Be unable to Create, Update or Delete page content on site Y

https://docs.google.com/spreadsheets/d/1cfc3-k9FklP1PD5xHjdTrL9x9jbGmm7EjlgvLTvX2Zw/edit#gid=0&range=70:70

Stephen's assumption is that the Drupal "trusted editor" role will be automatically assigned. 

Do we want to have a site member that can not do anything? General thought is no.
There will be no "microsite editor" role, we are repurposing the member role.

**Comment by finnlewis** [comment]
Need to decide whether to: 
 - add a group editor role
 - use the member role and communicate this as editor to microsite contorller.
 - something else?

**Comment by finnlewis** [comment]
From the start we've referred to 'microsite admin' and 'microsite editor'.

I think we should create the group level role of 'editor' and make sure they can manage content but not edit the site settings and theme config.

**Comment by stephen-cox** [comment]
Fixed with #191
