### ISSUE TITLE
Bug: News categories and news items from other sites available

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#217]
When more than one microsite instance is using News, and some Categories are in use

EG: https://site7.bathnes.localgovdrupal.org/news has 4 news items, and one is using the taxonomy term Education. If we select education we get the following page

![Image](https://user-images.githubusercontent.com/3852805/187493940-324022e8-6e11-4362-a009-8dc613fe2ea0.png)

showing the correct item from the site. 

Visit: https://site2.bathnes.localgovdrupal.org/news

There is 1 news item which does not have categories and yet the categories show a count of 1

![Image](https://user-images.githubusercontent.com/3852805/187494653-6efb2dae-1da0-4ade-a366-9825435a60b5.png)

Less important - as user 1 you can also see the content from other sites when you click the facet. A microsite admin does not, I haven't tested with the microsite controller.

**Comment by ekes** [comment]
So I think I'm right in saying the other entities are in the results, hence in the facet listing, but are filtered out after the fact by the entity access. The requirement here is, as with the entityquery alter, to remove them from the results in the first place. There is a content access (node access) plugin. We almost certainly can write a domain group access plugin - adding a field for the group to the index, and adding a filter on it based on the domain. The stretch goal here which would be the most useful for all and any use cases as yet un-imagined is to make an entity access version of the content access plugin... I'm not sure it's possible... I'll see if I spend a not insane amount of time wrapping my brain round it - falling back to the domain group only option (which should seem like a piece of cake by then).

**Comment by ekes** [comment]
https://www.drupal.org/project/3278349/issues/3307510

So the branch https://git.drupalcode.org/sandbox/ekes-3278349/-/tree/feature/3.x/search-api should do the domain filtering. It needs automated tests at the minimum, and caching checking. Manual tests appreciated.

If a content type is disabled in a group the content does not disappear as it 'should'. I'm not sure if allowing disabling content types with content is desirable, but it is possible with the current set up. This would require the stretch goal. I think I can now see how it could be done, but it needs thinking about particularly in relation to performance if there are a lot of groups. I'm reviewing the way node access is done in relation to this.
