### ISSUE TITLE
Write automated tests for creating a new microsite.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#225]
We're going to want some integration tests that cover the user journey of creating a new microsite and assigning users to the site. 

Specifically tests to cover: 

- [x] Microsite controller creates a new microsite on site1.domain.com
- [ ] site1.domain.com can be accessed anonymously
- [ ] Microsite controller creates a new microsite on site2.domain.com
- [ ] site2.domain.com can be accessed anonymously
- [ ] Content posted to site1.domain.com/node/1 cannot be accessed at site2.domain.com/node/1
- [ ] Content posted to site2.domain.com/node/2 cannot be accessed at site1.domain.com/node/2
- [ ] Add microsite admin 1 to site1.domain.com and log in as that user
- [ ] Confirm microsite admin 1 can create content in site1.domain.com

Any more for now @ekes @stephen-cox ?

**Comment by stephen-cox** [comment]
I've written a test for the Microsite creation form. There are already tests for the content and user creation and access. So I'm not sure if writing more tests for this stuff is necessary.
