### ISSUE TITLE
Group 3.x - estimate the work and timeline

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#229]
Just noting this here so we don't forget. 

@ekes we're in sprint planning and would like to try group 3.x sooner rather than later. 

It sounds like contact forms might work better in 3.x - and other things.

Let's discuss.

**Comment by stephen-cox** [comment]
This is the issue allowing config entities to become group content: https://www.drupal.org/project/group/issues/3292139

**Comment by ekes** [comment]
Upgrading is probably a whole bucket of work, and we depend on other modules in the ecosystem than just Group itself.

The first known-unknown is how complicated re-writing the basic permissions to use the new chained permission provider (and if that then negates the need to do the query alter). I discussed this with the maintainer, and gave an update a couple of weeks back. He seemed to think it shouldn't be too complicated... but... there's little documentation and examples. He was also very much in favour of rolling anything new out on Group 3 too.

In the ecosystem we need group permissions, that one isn't upgraded at all yet; group invite has a Group 2 version. I assume the European Commission needs to upgrade so they will have to go Group 2, before Group 3, with all those modules.

Timing is everything. The development of Group 3 is I admit sooner than I predicted it would be when we started this project. But still in the time frame we have remaining everything group related that we need isn't going to be ready in full UX and DX state for any release state.

**Comment by finnlewis** [comment]
It would be good to list out all the tasks / dependencies that need to be in place for Group 3 to work for us.

Some of this is re-writing our code. 
Some is awaiting modules that we depend on to be upgraded for Group 3

Modules we depend on: 
 - https://www.drupal.org/project/group
 - https://www.drupal.org/project/group_permissions
 - https://www.drupal.org/project/group_content_menu
 - https://www.drupal.org/project/ginvite
 - https://www.drupal.org/project/group_term 
 - https://www.drupal.org/project/domain_group

Also see https://www.drupal.org/project/group/releases/3.0.0-beta1

**Comment by finnlewis** [comment]
@finnlewis and @ekes to meet and discuss in more detail on Friday and flesh out the potential plan and timescales.

**Comment by finnlewis** [comment]
@finnlewis and @ekes to meet and discuss in more detail on Friday and flesh out the potential plan and timescales.

**Comment by ekes** [comment]
Example of the API change from grequest module being upgraded from 1.x to 2.x group support 
https://git.drupalcode.org/project/grequest/-/compare/1.0.x...2.0.x
and ginvite
https://git.drupalcode.org/project/ginvite/-/compare/2.x...3.0.x

**Comment by finnlewis** [comment]
### https://www.drupal.org/project/group

The 3.x branch is currently in beta. Ekes has played with it. It is nicer for some of the UI that we're not actually using for our users. 

See https://www.drupal.org/project/group/releases/3.0.0-beta1  for details of the differences. 3.x and 2.x 

Group 3.x is the future! Upgrading from 1.x to 3.x will take work.
 - Upgrading sooner rather than later might save work for councils.
 - The permissions system is different. Programatically determining access control should be more clear. 
 - Config entities can assigned to a group.  (eg Webforms, Vocabularies)
 
### https://www.drupal.org/project/domain_group

This ties domain to group. 

It provides the access control to say this content entity is in this group. Anything that can go into a group can also go into a domain. It extends the entity access query to check the domain and enforce the group. So if you are trying to access a content entity on the wrong domain, you will not be able to see it.

@ekes forked this here: https://www.drupal.org/sandbox/ekes/3278349 
We are using the sandbox version at the moment. 
This took @ekes a couple of weeks to write, so: 
  - he knows how it works
  - it should be quicker to update. 

Estimated dev time: 1 dev 1 sprint 

### https://www.drupal.org/project/ginvite

This is largely upgraded, see: 
https://git.drupalcode.org/project/ginvite/-/compare/2.x...3.0.x?from_project_id=64219

Might need some tweaking / testing for 3.x, only 2.x at the mo. 

Estimated dev time: 1 dev 2 / 3 days 

### https://www.drupal.org/project/group_content_menu

@ekes suggests looking at gnode and ginvite for a lead on how to upgrade this to 3.x 

Once we've reviewed ginvite, this should be quicker. 

Estimated dev time: 1 dev 1 day 

Only looks to be a 1.x branch. Might be easier in Group 3.x as config entities are supported. 

### https://www.drupal.org/project/group_term  

@ekes suggests looking at gnode for a lead on how to upgrade this to 3.x 

This could be just search and replace on methods and names. 

Estimated dev time: 1 dev 1 day 

### https://www.drupal.org/project/group_permissions

No idea! Let's ask [LOBsteRR](https://www.drupal.org/u/lobsterr). 

See: https://www.drupal.org/project/group_permissions/issues/3308272

Sounds like it is in hand and will be worked on soon! 

Also see https://www.drupal.org/project/group/releases/3.0.0-beta1 

Estimated dev time: ???? none if LOBsteRR does it.... but there doesn't appear to be a huge amount of code. 

### Our custom code: 

Most of our custom code that depends on Group and related APIs is altering forms / labels / UI / behaviours like adding roles. @ekes currently thinks that upgrading might not be a difficult task, just tedious to go through, refactor and test. Some of our automated testing might need updating, but the test coverage should also help to identify things that are broken.

Estimated dev time: 1 dev 1 sprint

**Comment by willguv** [comment]
@finnlewis @ekes can I get a walkthrough of all of this early next week, might have to be slow as there’s a lot I don’t get. Feels critical to understand though. Thanks

**Comment by finnlewis** [comment]
Just a note: @ekes  and I did some further estimation on a spreadsheet here: https://docs.google.com/spreadsheets/d/1lJx_MC_FpwYfKF7y4lZ0ESlYoE2LcH6vslDl-T-t8xI/edit#gid=1537911030

Summary: we are confident that we can get the upgrade to Group 3.x done within two sprints.
