### ISSUE TITLE
GroupContent as the site content; or Node 

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#23]
The GroupContent (a content relation between the group and its content - in this case Node) at the moment is just that, and displays only the title. The content that is used for the site is the node itself. This is also set for the permissions (note #20) so the node is visible to the anonymous user.

Discussion:-

It is possible to load and display the Node on the GroupContent and make this the 'content', hiding the original Node. This was something that @markconroy mentioned they are doing with some of the University sites. It means the content /node/_x_ is also visible on /group/1/content/_y_ and even on /group/2/content/_z_. In a single site you then want to rabbit hole the /node/_x_ with our set up this wouldn't even be needed.
In our use case only the GroupContent /group/1/content/_y_ is visible on the domain assigned to group 1; and it would even be possible to have the same node on GroupContent /group/2/content/_z_ on the domain assigned to group 2. Path aliases would also be set on the GroupContent per group.

@markconroy can you remember: were there any adverse UX issues for editors, or other quirks; issues for theming; loading content, or fixes that you needed to make this a good option?

Generally it seems like it might be a good idea.

**Comment by markconroy** [comment]
@ekes to get more than just the title to display, you need to go to 
Groups > Microsites > Content > Page > Manage Display > Title 

And set "Title" as "rendered entity", and choose view mode "Full".

There wasn't any major issue with theming. One issue we had was that since we (the university site I was working on) have our page titles inside our full view mode templates for semantics, the page title was getting rendered 2 times - via block AND via our template. But that's an easy fix. 

The other thing was that there were 2 article tags, one from the group-content.html.twig file and one from the node.html.twig file, so we ended up with this:

```
<article class="group-content">
  <article class="node">
  </article>
</article>
```

To get aroudn that, I just removed everything from the group-content template and let that render only `{{ content }}`

**Comment by ekes** [comment]
One more vote for Group Content https://github.com/localgovdrupal/localgov_microsites_group/pull/41 as it saves having to do anything complicated to add the group context for the menu if everything is displayed under the group context anyway.

**Comment by ekes** [comment]
Questions: Aliases, paths, breadcrumb, admin theme

When in the group context the breadcrumb becomes something like groups > group name > content
However we don't want to include the group in the breadcrumb if it's shown on a domain. The piece of content could be the homepage and then other content could be under it.

Aliases UX: The alias is set on the Group Content relationship entity. There is also an alias on the node which would be the form people are editing. How to handle the two forms? Can we enforce, and maybe hide from the user, that the alias always has the group alias first to prevent url alias clashes.

Aliases: Could we automatically add, and remove, the group path, from the Group Content alias in the inbound and outbound processors on the group domain. I know I've thought about this before and discounted it for some reason. Maybe just need to try implementing it and see what the issues are.

Admin theme consistency: at the moment anything in the group context is in the admin theme, thus giving consistency. There would need to be an additional rule such that _some_ group content when _view_ed is shown in the front end theme, but not others, so for example: Node GroupContent view front end theme, Menu GroupContent admin theme.

Tasks tabs: Which ones where? Edit -> node edit cf. alias issue above; Delete -> ?. If part of this is that content can be shared, or edited on the control site, there is a difference between deleting the relationship (removing from the group) and deleting the node (removing from any group).

**Comment by markconroy** [comment]
> When in the group context the breadcrumb becomes something like groups > group name > content
> However we don't want to include the group in the breadcrumb if it's shown on a domain. The piece of content could be the homepage and then other content could be under it.

We could remove the first or second item from the breadcrumb index perhaps?

> Aliases UX: The alias is set on the Group Content relationship entity. There is also an alias on the node which would be the form people are editing. How to handle the two forms? Can we enforce, and maybe hide from the user, that the alias always has the group alias first to prevent url alias clashes.

We probably don't need an alias on the node, just /node/[nid] should be enough since _all_ content should be group content. As all, all content should reside within at least one group for it to appear on any microsite.

> Aliases: Could we automatically add, and remove, the group path, from the Group Content alias in the inbound and outbound processors on the group domain. I know I've thought about this before and discounted it for some reason. Maybe just need to try implementing it and see what the issues are.

If we remove the group path, we might end up with clashing URLs, such as two groups that have an "About Us" page both wanting to use /about. I wonder is there a way to remove the group part within the domain instead of within the controller site?

> Admin theme consistency: at the moment anything in the group context is in the admin theme, thus giving consistency. There would need to be an additional rule such that some group content when _view_ed is shown in the front end theme, but not others, so for example: Node GroupContent view front end theme, Menu GroupContent admin theme.

I agree

> Tasks tabs: Which ones where? Edit -> node edit cf. alias issue above; Delete -> ?. If part of this is that content can be shared, or edited on the control site, there is a difference between deleting the relationship (removing from the group) and deleting the node (removing from any group).

If we don't have an alias for the node, then this shouldn't be an issue.

**Comment by ekes** [comment]
>  If we remove the group path, we might end up with clashing URLs, such as two groups that have an "About Us" page both wanting to use /about. I wonder is there a way to remove the group part within the domain instead of within the controller site?

That was the inboud outbound processor idea. Enforcing the group/name on the actual alias (but probably hiding it in the field - which has to be separate from the node form) and then removing (and defaulting) based on domain.

**Comment by ekes** [comment]
> If we don't have an alias for the node, then this shouldn't be an issue.

Still want to be able to have consistent way getting from the 'GroupContent' node to:
 * editing the node (Node edit form)
 * setting the path alias (GroupContent edit form)
 * removing the content (cf. difference between deleting the GroupContent or Node especially if possibility of shared content)

**Comment by markconroy** [comment]
In Annertech, we created "Local Tasks" and placed them in the tabs region for 

"Edit Content (node) | Edit building block (layout builder items) | Manage (Group content)", but they were only available from the group content entity. If you were looking at the node, you got the usual node items "View | Edit | Delete"
![Screenshot 2022-05-20 at 14 59 24](https://user-images.githubusercontent.com/2183332/169543988-8a579f22-7df1-4607-b156-0dcbd01bcf0e.jpg)

**Comment by stephen-cox** [comment]
If we go with showing node content rather than group content we run into the issue of contrib modules relying on finding the group from the Drupal route.

This is a problem with the blocks displaying menus from the [Group Content Menu](https://www.drupal.org/project/group_content_menu) project. We have hacked this for now see #41 

Also worth checking how [Group Media](https://www.drupal.org/project/groupmedia) works if we're thinking of introducing of using this.

**Comment by ekes** [comment]
The decider on this one is probably going to be how Directories, News etc. are designed. Their indexes, and views, are built around linking to the nodes; the nodes flag where they are with an entity reference field to another node. Guides, services all work like this. There doesn't seem a simple way of reusing these components but linking to a different entity.

The context however will rear it's head if we don't always come under /group/{group)/* paths. The #41 issue however can be better fixed, for domains, by [creating a new context](https://git.drupalcode.org/sandbox/ekes-3278349/-/commit/90891d9278d00e53d8867e41a727aabd5eed6904). This doesn't work for the control site however, it could be extended to _also_ look for the (first) GroupContent entity referencing and Entity, if it's required that the control site also works.

Open question 1: Do we need be able to display the sites within the control site correctly? If so we'd certainly need to restrict content to only one group (or explain that it only is displayed as in one group).
Open question 2: Are there other places that context is drawn from the route - checking Group Media now - where we need to work out how to add context. Can they all be extended easily like core context.
Open question 3: How to do aliases https://github.com/localgovdrupal/localgov_microsites/issues/146 - or maybe that is just a follow-up issue.

**Comment by ekes** [comment]
> Open question 2: Are there other places that context is drawn from the route - checking Group Media now - where we need to work out how to add context. Can they all be extended easily like core context.

Group media checks the route https://git.drupalcode.org/project/groupmedia/-/blob/8.x-2.x/modules/groupmedia_paragraphs/groupmedia_paragraphs.module#L63 but it is looking at the group or other entity and calculating the group for an edit situation. I'd guess this is common. Like even without our use-case when editing node/1 a module might want to know which groups it's associated with.

So no additional complexity there at least.

**Comment by ekes** [comment]
With previous work and now https://github.com/localgovdrupal/localgov_microsites_group/pull/129 have we got all of these?

**Comment by ekes** [comment]
@finnlewis @stephen-cox @msayoung 

Has anyone noticed anywhere this is still an issue: the GroupContent entity (rather than the Entity - node, user) being presented?

If not I'd propose closing this as done; and opening new specific issues, for user maybe, or for tabs showing, or whatever gets spotted in the future (user testing) and then fix them, or look for a neater solution.

**Comment by finnlewis** [comment]
I've not seen it anywhere recently.
