### ISSUE TITLE
Breadcrumb on node create form contains link to hidden site content page

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites_group#245]
![image](https://user-images.githubusercontent.com/7189914/188875953-f96fe31f-208c-41d8-b2f9-551de3110a46.png)

Clicking 'All entities for Site 1' leads to 

![image](https://user-images.githubusercontent.com/7189914/188876241-7957b85e-5a65-4ce5-b505-cc293b89b9ae.png)

**Comment by finnlewis** [comment]
No idea how to fix this! 

hook_breadcrumb_alter() ?

**Comment by stephen-cox** [comment]
It's not east to remove links from a breadcrumb using `hook_system_breadcrumb_alter()`. There is a patch, which is pretty straightforward: https://www.drupal.org/project/drupal/issues/2966004

**Comment by stephen-cox** [comment]
PR #258 Redirects the content listing page to the node listing page, which is easier than patching core to change the breadcrumb links.
