### ISSUE TITLE
Change "Member" to "Editor" role globally?

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#248]

**Comment by willguv** [comment]
My hunch is council teams understand what editors can do, more than what members can do. We should use terms that are more familiar to them

**Comment by msayoung** [comment]
In the Microsites WG the councils felt they were comfortable with "Members" as a catch-all term for the Editors and Admins on a Microsite. 

@willguv - happy to close this for now, and reopen if we find its a problem later?

**Comment by willguv** [comment]
@msayoung I'll go with it, but not convinced :)

This came from having a fake editor checkbox to make the editing capability clear. Did we decide anything about that?

Thanks again
