### ISSUE TITLE
Editor cannot delete content (own or others)

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#250]
An editor should be able to delete content. 
Do we want to restrict this to their own content, or any content? 

@finnlewis @willguv thoughts?

**Comment by msayoung** [comment]
@finnlewis - can you confirm that's what we want ^^^

https://github.com/localgovdrupal/localgov_microsites_group/pull/257

**Comment by willguv** [comment]
@msayoung if we're following LGD core, I think editors can delete any content. Many people in a team may have to manage a microsite in this way

**Comment by finnlewis** [comment]
> editors can delete any content

Yes, sounds right to me.
