### ISSUE TITLE
Allow for coloured background sections (in the paragraph layout sections)

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#251]
I started experimenting with this for fun. 

I see it working in this way:

On the page_section paragraph type we add another custom field called Colour Scheme (or something). This allows the content editor to pick from a number of Colour scheme options (labelled: Colour scheme 1, colour scheme 2)

We then add a class to the `paragraph--localgov-page-section.html.twig`

If nothing else is done, nothing will happen if these fields are populated. 

LocaGov Drupal Core
For this to work in the main setup, the theme will need to define some custom colour schemes. This will probably require at minimum
- the background colour
- text colour

LocalGov Microsites
I suggest we add some more fields to the Microsite entity, defining the Colour Schemes. 

The complexity may be in further overrides for components placed within these sections. 

Questions. 
- Will we want to use this concept of colour schemes on and of the other paragraphs?
- should we use the same naming as localgov_media_with_text which offers "Default" and "Featured" styles ?

**Comment by msayoung** [comment]
@markconroy - I wonder if you have any thoughts on the above?

**Comment by markconroy** [comment]
I'd definitely like to figure out a way for this to work.

Even if we didn't go with full on colour schemes, I can see that getting tricky to handle with so many potential variables, we could go with perhaps 2 fields

1. Background colour (color picker or select list)
2. Is the background colour dark (boolean)

Then we can have a class to add to the paragraph for the background colour, or an inline style. Following that, we'll use the "is this dark" boolean to set the foreground colours - text, etc.

We should probably have a call about this, it will be exciting.

**Comment by msayoung** [comment]
Summarising our chat just now. 

We'll add a background colour select list with the following options: 

1. none, 
2. accent colour, 
3. light grey

The accent colour will pick up the `--color-accent` css variable, and we'll create a new `--color-accent-contrast` variable for the text. 

lightgrey will set the background colour to a light grey.

We'll apply extra padding if there's a background colour set. 

Note: the page section paragraph type isn't installed in core by default, as the page templates don't currently work with full width sections. @markconroy were you proposing to rewrite those templates as part of this too? 



After we have this in core, we'll look at how to extend in microsites - ie whether any elements (eg featured teaser) needs different treatment when it's on a accent colour background).

**Comment by markconroy** [comment]
>  @markconroy were you proposing to rewrite those templates as part of this too?

Yes, ma'an, I was!

**Comment by msayoung** [comment]
Great work so far @markconroy :) 


So I have had a look at what happens out of the box with microsites, assuming we set  Accent 1 to our `  --color-accent` and the Accent alt to  `--color-accent-2`

## On Accent 1 background

- Accordion titles remain black, while other text recolours
- Call out box uses a background colour of --color-accent
- There is a text formatting option (Primary) which uses -- color accent as a background colour
- Link colour is currently set to --color-accent (though it can be overridden)

## On Accent 2 background

- Captions (with images) use the --color-accent-2 as a background colour
- Featured teasers use the --color-accent-2 as a background colour

I'll take a look at sorting these.

**Comment by msayoung** [comment]
## General 

Accent 1: Link colour is currently set to --color-accent (though it can be overridden)

## Accordion

- [x] Accent 1: Accordion titles remain black, while other text recolours
- [ ] Icons need recolouring

## Call out box 

- [x] Accent 1: Call out box uses a background colour of --color-accent
- [x] Accent 2 and 3: link text doesn't follow text colour.

## Image with caption

- [x] Accent 2: Captions (with images) use the --color-accent-2 as a background colour

## Featured Teaser

- [x] Accent 2: Featured teasers use the --color-accent-2 as a background colour
- [x] Accent 1 & 2 : Heading and link text don't follow text colour


## Media with text

Seems fine

## Link

- [ ] Icon needs recolouring

## IA block

- [x] Accent 2: Promoted IA block background colour same as section background
- [x] Accent 2: Normal IA block background colour (should be transparent?)
- [x] Accent 1: Text and link colour 
- [ ] All backgrounds: need padding


## Text

- [x] Accent 1: There is a text formatting option (Primary) which uses --color-accent as a background colour

## Quote

- [x] Accent 1: Quotee text color
- [x] Accent 2: Background colour

## Table

Ok as has a border.

## Video

## Embed content lists

**Comment by markconroy** [comment]
Is there anything you need me to look at here?

**Comment by msayoung** [comment]
All in here: https://github.com/localgovdrupal/localgov_microsites_base/pull/126 apart from recolouring the icons which we may want to tackle in localgov_base

**Comment by msayoung** [comment]
Have opened another task to discuss icons https://github.com/localgovdrupal/localgov_microsites_base/issues/129
