### ISSUE TITLE
Disabling News also disables events

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#252]
Also a problem with Blogs

**Comment by finnlewis** [comment]
note: the code for this might change in Group 3.x, but @ekes is surprised that this is still a big.

**Comment by stephen-cox** [comment]
It looks like blogs, events and news all share some permissions to do with taxonomy terms which is why this is a problem.

I think we'll need to work out how to exclude some permissions from the logic that works out how to switch stuff off.

**Comment by stephen-cox** [comment]
I reworked the logic used to disable modules in https://github.com/localgovdrupal/localgov_microsites_group/commit/45ca3dbd50535e08c06d07d98d22f493a2998e7c

Things how work when testing through the UI, but the GroupPermissionsHelperTest::testToggleModulePermissions() test now fails

**Comment by finnlewis** [comment]
This will need re-writing for Group 3.x :)

**Comment by finnlewis** [comment]
Closing this in favour of
https://github.com/localgovdrupal/localgov_microsites/issues/304
and

**Comment by finnlewis** [comment]
This is fixed!
