### ISSUE TITLE
Allow trusted editors to see and revert revisions.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#259]
At the moment it seems that we can't see or revert revisions.

I suggest that: 

As a trusted editor
I want to view, revert and delete all revisions
So that I can step back to previous versions of content.

**Comment by finnlewis** [comment]
@willguv just sense checking with you, but this seems like an obvious omission at present.

**Comment by willguv** [comment]
@finnlewis thanks for the heads up - this seems essential if it's not lots of work

**Comment by finnlewis** [comment]
First, let's work out why we can't see revisions at all on the control site.

**Comment by msayoung** [comment]
There is a bug with Group and Revisions. 
If you add content not associated to a group you can see the Revisions, but not when its group content. 

https://www.drupal.org/project/group/issues/3256998

I assume we should leave this til Group 3.x 
@finnlewis ?

**Comment by finnlewis** [comment]
Aye - let's hold off for now

**Comment by finnlewis** [comment]
Ready to test against Group 3.x

**Comment by msayoung** [comment]
@finnlewis this is now working with Group 3.x however, we dont have access to the Revision log field. 

Looks like this is being worked on here: https://www.drupal.org/project/drupal/issues/2959611 

How urgent is this, do you think?

**Comment by finnlewis** [comment]
Not too worried about the log field for now. Let's make sure revisions work and we can come back to the revision log field if/when needed.
