### ISSUE TITLE
Admin (default) permissions

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#26]
We need to confirm that the 'microsite admin' has the correct permissions in the microsite when created.

### Acceptance tests: 

1. Log into a microsite as the microsite admin
2. Be able to edit the configuration of design
3. be able to manage content.
4. Not see anything else they don't want to see.

**Comment by ekes** [comment]
This *is* going to be more interesting than a 1. 

Everything can be sorted with [3f2dabc] but then there's no access to create menu items. The issue is https://www.drupal.org/project/group_content_menu/issues/3152938 the microsite admin needs to have permission to `administer group` at which point all the tabs we've just hidden reappear as that's the override permission that can do all the things to and in a group.

**Comment by ekes** [comment]
https://www.drupal.org/project/group_content_menu/issues/3280653

**Comment by msayoung** [comment]
May be dealt with elsewhere but admins can't currently add the Page content type. Shall I create another issue for that @ekes ?

**Comment by ekes** [comment]
That's a bug. They do have the permission to add a page, just don't get to that form, or at least on my site. So new issue I'd say, looking at it:

If you go to https://localgov-micro-1.lndo.site/group/1/content/create/group_node%3Alocalgov_page
(and are the admin of it you can add a page).

The action button on https://localgov-micro-1.lndo.site/group/1/nodes is visible too

But it goes to https://localgov-micro-1.lndo.site/group/1/node/create which would list the content types, which it doesn't, and also as there is only one content type it should automatically redirect to https://localgov-micro-1.lndo.site/group/1/content/create/group_node%3Alocalgov_page which it also doesn't.

**Comment by ekes** [comment]
So taking this as fixed.

With a PR for the additional content type list bug #45 deal with there.
