### ISSUE TITLE
Bug: Microsite admin menu gone from "Content"

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#261]
![Image](https://user-images.githubusercontent.com/3852805/190154256-3d557687-00f2-4008-86b7-8f5be599a7ad.png)

**Comment by msayoung** [comment]
Bug introduced as part of this: https://github.com/localgovdrupal/localgov_microsites_group/pull/210

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/262#pullrequestreview-1135841997
