### ISSUE TITLE
Domain Path PathAuto

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#271]
- [x] Create three pathauto aliases for same value, they _are_ created `string`, `string-1`, `string-2` _but_ `string-1` is also replaced as the link _to_ the content for `string-1`. At least that's my manual testing of https://www.drupal.org/project/domain_path/issues/3285213 Needs automated tests and a fix
 - [x] Pathauto checkbox is always _off_ by default, no way of changing this, you have to select it
 - [ ] We probably want to extend the automatic replacement to use group alias rather than `-1` in the first instance

_Originally posted by @ekes in https://github.com/localgovdrupal/localgov_microsites/issues/146#issuecomment-1168568432_

**Comment by ekes** [comment]
Realistically it would be better to change the design of the module to map better to the way that path / pathauto does it with a 'field' (that has no schema) and a widget for it. Rather than the current form alter situation. So the proposals are the minimum band-aid to get the domain_path_pathauto working; but the proper one is a bigger rewrite.

**Comment by stephen-cox** [comment]
@finnlewis @ekes I have evaluated the Domain Path Pathauto and I believe the latest dev version with a couple of patches to fix some bugs will do what we need; at least it fixes the first 2 issues listed above. There's a draft PR with these changes here #272; I still need to write some tests, but some feedback to ensure this is going to work for us would be appreciated.

I still have some questions:

@ekes I'm not sure what you mean by

> We probably want to extend the automatic replacement to use group alias rather than -1 in the first instance

The current config uses the Drupal wide Pathauto patterns. We have some code deleting these for all content type apart from Blogs. It strikes me this is better than nothing at all, but would it be better to set some defaults for each site and have these editable?

It looks like the domain_group_alias module should allow this, but it currently throws errors. At a minimum, I'll look at getting this fixed.

**Comment by stephen-cox** [comment]
Having taken a look at the [domain_group_alias](https://git.drupalcode.org/sandbox/ekes-3278349/-/tree/3.x/modules/domain_group_alias) module, this is for setting aliases on group content, but we're not using group content and when setting paths we're doing this on the node (although they vary by domain).

It provides a UI for setting aliases by content type on the group, but as these are URLs to group content that we're not using I'm not sure how useful this is. It is the end of the day and so my brain is starting to melt, so not sure if this is 100% correct.

Going back to the requirements here, do we want site admin and/or microsite controllers to be able to set pathauto patterns on a site by site basis?

**Comment by ekes** [comment]
> @ekes I'm not sure what you mean by
>> We probably want to extend the automatic replacement to use group alias rather than -1 in the first instance

I had to think too! The `-1` refers to the `string-1` automatic appending of an incrementing number. Guess my idea was replacing conflicts with the domain alias. But I'm not sure.

> domain_group_alias module 

I've not done anything with this module as of yet - it's very much whatever was in the original domain_group module.
