### ISSUE TITLE
Select theme override - check permissions for microsite admin

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#273]
Microsite admin cannot chose the theme

**Comment by msayoung** [comment]
Debugging this. Currently the permission we need is created at the sitewide level, rather than the group level. 

We could assign the controller this permission. But I think we want the microsite admin to be able to set the default theme.

**Comment by finnlewis** [comment]
See https://github.com/localgovdrupal/localgov_microsites_group/pull/274
