### ISSUE TITLE
Controller role

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#28]
Create the role and set sensible default permissions!

Acceptance tests: 

- [x] Log in as a 'Microsites controller' 
- [x] See just the things I need to see (just user management and microsites management)

**Comment by finnlewis** [comment]
@ekes are you already on this or would this be a good one for me to chip in on?

**Comment by ekes** [comment]
Not one I'm working on. So feel free to make a role.

**Comment by ekes** [comment]
@finnlewis Guess we can push this one to done?

**Comment by finnlewis** [comment]
Oh yes, I do believe we can! Thanks @ekes
