### ISSUE TITLE
upgrade custom code for Group 3.x compatibility

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#290]
Most of our custom code that depends on Group and related APIs is altering forms / labels / UI / behaviours like adding roles. @ekes currently thinks that upgrading might not be a difficult task, just tedious to go through, refactor and test. Some of our automated testing might need updating, but the test coverage should also help to identify things that are broken.

Estimated dev time: 1 dev 1 sprint

**Comment by finnlewis** [comment]
Closing this in favour of individual bugs
