### ISSUE TITLE
[3.x] Duplicate content in listing

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#294]
Goup 3.x seems to display duplicate listings of existing group content nodes.

Fresh install, one default node, shows this at https://localgov-micro-1.lndo.site/group/1/nodes  

![image](https://user-images.githubusercontent.com/326588/201883207-7ff41864-11db-42ba-81d9-b795dcc6cfca.png)

But all link to the same node.

Known issue, see: 

https://www.drupal.org/project/group/issues/3315779

**Comment by finnlewis** [comment]
@ekes Have you tested the patch on https://www.drupal.org/project/group/issues/3315779 ?

https://www.drupal.org/files/issues/2022-10-28/group_module_member_3315779_9.patch

**Comment by ekes** [comment]
Nope. Was leaving it to see if there was some feedback on the solution before spending some time. But applying it in the interim is also good.

**Comment by finnlewis** [comment]
OK - will give it a try

**Comment by finnlewis** [comment]
Patch seems to help! 

https://github.com/localgovdrupal/localgov_microsites_group/commit/560fc9fc34bee1c62fb12ad0b891d8f8130eba2e

![image](https://user-images.githubusercontent.com/326588/201892269-451b1b79-66f8-4000-a768-3acff29d155a.png)
