### ISSUE TITLE
[3.x] Group Permissions page

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#296]
Needs re-doing.

**Comment by ekes** [comment]
It's working for some reasonable value of working. Tests need updating.

**Comment by ekes** [comment]
Meh. No it's not quite there.

**Comment by finnlewis** [comment]
This is specifically for our page with the enable / disable content types in our microsite admin form.

Also see https://github.com/localgovdrupal/localgov_microsites_group/issues/296
