### ISSUE TITLE
Rename tabs and views

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#30]
As per localgovdrupal/localgov_microsites#36

**Comment by ekes** [comment]
Related can we just import our own views for users and nodes membership for the views that are presently not installing #27

**Comment by finnlewis** [comment]
@ekes would this be another good one for me to help with?

**Comment by ekes** [comment]
It's really fixed in #27 which is fun if you want to look at it further; for now I'm just importing our views with our naming, but will need further work at some point to make it less brittle.

**Comment by ekes** [comment]
@finnlewis Set to done with followup on #27?

**Comment by ekes** [comment]
Closing this in favour of #36 and #27
