### ISSUE TITLE
[3.x] Missing add new content button

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#300]
Fresh install.
Create new microsite.
Create admin1 user and assign to microsite as an admin.
Log into microsite 1 as admin1
Go to https://localgov-micro-1.lndo.site/group/1/nodes

Can see 'add existing content' but not 'add new content'

![image](https://user-images.githubusercontent.com/326588/201894341-b89c4b4b-04b9-47bd-b276-8a64873c1633.png)

**Comment by ekes** [comment]
Should be fixed.
