### ISSUE TITLE
[3.x] Imported permissions not working

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#302]
Seems to need a cache clear to bump the microsite home page into place.

**Comment by finnlewis** [comment]
@ekes This actually seems to be a permissions issue.

I can see the page logged in but not logged out.

**Comment by finnlewis** [comment]
In the watchdog log I see: 

> 
Path: /. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 118 of /app/web/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).

Is there a quick way to identify what is denying access? Something akin to Devel node access https://www.drupal.org/project/devel_node_access?

**Comment by ekes** [comment]
Imported permissions issue https://www.drupal.org/project/group/issues/3311949#comment-14788688

**Comment by ekes** [comment]
Might actually be fixed now.

**Comment by ekes** [comment]
This has been moved to done, but not closed. Seeing it's not been highlighted in the last 5 days I'm assuming fixed.
