### ISSUE TITLE
[3.x] Microsite groups not listed at /admin/microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#304]
Hey @ekes 

Just did a fresh install, created a microsite and I can't see it in the list of microsites.

![image](https://user-images.githubusercontent.com/326588/202424089-38beaf7e-fab5-49fb-a362-8decaea5cd77.png)

I do see it at https://localgov-micro-1.lndo.site/ though.

**Comment by finnlewis** [comment]
Interestingly, I can get to the group config at https://localgov-micro.lndo.site/group/1/

But no microsites listed at https://localgov-micro.lndo.site/admin/microsites
And no groups listed at https://localgov-micro.lndo.site/admin/group

**Comment by ekes** [comment]
Yer you've got view permissions. The two things that have changed are:
 * group permissions was installed
 * the admin role is no longer a _real_ admin role and just has permissions 

So things to test: add all permissions to the admin role, is it that? Does the list work again then?
If not try uninstalling group permissions (somehow).

**Comment by ekes** [comment]
Yep. It's a permission.

Now. The only users that should see this list are controller's right? In which case I'm closing it in favour of the task that will fix it https://github.com/localgovdrupal/localgov_microsites_group/issues/305
