### ISSUE TITLE
[3.x] No content types available at /group/1/node/create

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#306]
1. Create microsite 1.
2. Create admin1 user, assign to microsite as a admin role.
3. Log into microsite 1 as admin1
4. Visit: https://localgov-micro-1.lndo.site/group/1/node/create

No links to add content: 

![image](https://user-images.githubusercontent.com/326588/202458530-6561a387-0b2b-443b-8a6d-c6f4745dc080.png)

**Comment by ekes** [comment]
Think this is fixed in group. Can you checkout the head of the 3.x branch. So 3.x-dev of group module.

**Comment by finnlewis** [comment]
Yay! Latest from https://git.drupalcode.org/project/group does indeed resolve this! Thanks @ekes !
