### ISSUE TITLE
[3.x] Bug: Add new content list is wrong / unavailable

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#315]
As a microsite admin I can't add new content. 

As a microsite controller I can, although the list of content is wrong.

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/202744252-c5aa3ce8-3cde-4a8b-a52e-33e5d8efd91d.png)

**Comment by ekes** [comment]
What do you see as admin? Because I see that list, at least with my present install.

Also what's wrong with it except the already discussed issue https://github.com/localgovdrupal/localgov_microsites_group/issues/298

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/202749958-dff38be4-6e59-4f02-a9d6-58dcf3db875a.png)

**Comment by msayoung** [comment]
So I guess it'll be resolved when the other issue is.
 I realise I can actually create new content if I can remember the correct path to do so just can't see the links from the Content tab

**Comment by ekes** [comment]
Have you got the dev version of group module. It (the missing list) looks like an issue we were discussing that's fixed there.

**Comment by msayoung** [comment]
Tested again. The problem is the add new content list. 
For controllers the list is wrong
For microsite admin and microsite editor the list is missing.

**Comment by msayoung** [comment]
This is now fixed on a fresh install - thanks :)
