### ISSUE TITLE
Some Embddedable views not installing

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#324]
The lgms_embed_view_events and lgms_embed_view_news views are not installing. 

lgms_embed_view_blogs is installing fine. 

_might_ be the     - group.relationship_type.group_relationship_type_5a3c3717 dependency ?

**Comment by msayoung** [comment]
currently blocked on testing https://github.com/localgovdrupal/localgov_microsites_group/pull/325 as I can't create the items needed to test because of #326

**Comment by ekes** [comment]
Can you remove the URL field from the form for now to be able to save content and test this?
