### ISSUE TITLE
Restrict permission to edit Media by group

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_microsites_group#348]
Currently autheticated users can edit any media on any group. Probably want to restrict this

**Comment by willguv** [comment]
@msayoung feels like this should be considered for 11/12 although would like to understand size/ complexity

**Comment by finnlewis** [comment]
We're going to use https://www.drupal.org/project/groupmedia

We need to test this against 3.x, so probably best to wait until the 3.x work is far enough along.

**Comment by finnlewis** [comment]
- [x] Test this in current form, start new branch
- [ ] Liaise with maintainer to push towards a release

**Comment by finnlewis** [comment]
Seems to mostly work with vanilla install, but some bugs with content editing on Group3.x  limited ability to test.

Now that we have the microsites profile installing we need to test group media with our profile.

**Comment by finnlewis** [comment]
OK - now that I have a fresh localgov_microsites install working with content creation, I've tested again.

This workflow appears to be working: 

1. enable group media module
2. enable "Group media (Image)" plugin at https://localgov-micro.lndo.site/admin/group/types/manage/microsite/content
3. grant permissions for admin to do all the group media things at https://localgov-micro.lndo.site/admin/group/types/manage/microsite/permissions
4. log into site 1 as admin 1
5. go to media tab at https://localgov-micro-1.lndo.site/group/1/media
6. Create media and save
7. Edit a node, click to add an image paragraph
8. See the image 
9. Log into site 2 as admin 2
10. Go to https://localgov-micro-2.lndo.site/group/2/media
11. note that the image media added to site 1 is not visible
12. Create media and save a new image to site 2
13. edit a node
14. add image paragraph and add media
15. see media library with just the image uploaded to site 2

BUT

This workflow does not work:

1. log into site 1 as admin 1
2. Edit a node, click to add an image paragraph
3. Add media
4. browse to upload a new image
5. see image media entity form with alt text and crops
6. add alt text etc.
7. save
8. expected result: see the image in the media library
9. actual result: don't see the image in the media library

So uploading a new image via a paragraph image field or via media embed in CKEditor does not seem to place the iamge media into the group / microsite.

**Comment by finnlewis** [comment]
@stephen-cox @ekes 

I've yet to work out why media is not associated with a group when added from a modal from media library. 

There is a branch here: https://github.com/localgovdrupal/localgov_microsites_group/tree/feature/348-group-media

A draft pull request here: https://github.com/localgovdrupal/localgov_microsites_group/pull/353

I've been stepping through the code that appears to attach media to group in different scenarios: https://git.drupalcode.org/project/groupmedia/-/blob/4.0.x/src/AttachMediaToGroup.php#L106

I also note that there is a hook_entity_update but no hook_entity_insert, in the module file, see: https://git.drupalcode.org/project/groupmedia/-/blob/4.0.x/groupmedia.module#L35

So maybe the way that media entities are created normally triggers the update but when adding from a modal does not. 

If either of you can take a look , please do dive in. It would be really good to have this working smoothly.

The work around is to force adding media via the group media tab, which does seem to work. 

Thanks guys!

**Comment by ekes** [comment]
> This workflow does not work:

So it does call the ::attach method for the File entity, but it has no context to get a group from. 
eg. You're on /group/1/content/create/group_node%3Alocalgov_blog_post so a route with the {group} in it
But when adding an image via the library the route is just media_library.ui with no parameters. It wouldn't be until you select an image and attach it to the node that it could get the group from the node relationship. But of course you can't select the image as it's not in the gallery.

A quick fix for us would be to implement `hook_groupmedia_entity_group_alter()` and get the group from the domain and attach it.

I'll do that.

**Comment by finnlewis** [comment]
Sounds like a plan!

**Comment by ekes** [comment]
Grr.. not so simple as it only adds it if it is an entity on an entity in relation or group. So when you add media directly it's group is doing the work. When you add one indirectly groupmedia does it because it's referenced by a field on an entity in a group. Now to teak how groupmedia works further _or_ just do it in our code. Or think of something better.

**Comment by ekes** [comment]
[563987e](https://github.com/localgovdrupal/localgov_microsites_group/commit/563987ea588ad92bb02d99c52bb674d88e76c9b7) does it for the media library form; are there more forms. It seems (see commit message) targeting the specific forms is the way forward.

**Comment by finnlewis** [comment]
@ekes you beauty! That does indeed work well for the media library form.

I will continue to test and see which other forms we might need to include.

**Comment by finnlewis** [comment]
Merged, nice work people!
