### ISSUE TITLE
Add menu bar for microsite admins to be able to find their group

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#35]
When a 'microsite admin' logs in we want to redirect them to the group page.

Like /group/1

However, if they are elsewhere, we need to offer a link or links so that they can manage their content and config (admin toolbar ? custom block displaying the tabs of the group?)

**Comment by ekes** [comment]
@markconroy @msayoung Before I make a blank-ish template for this does the render array make sense to you https://github.com/localgovdrupal/localgov_microsites_group/commit/5b881e96ac64218ff3e1773505964400ebc13393#diff-31a6feeb998ebe17cbedc629279f120b16a3db15468702d0ca85b21e486654ddR118=

It's basically an array of links with #access and #weight.

**Comment by markconroy** [comment]
@ekes  

1. Do we have a fall back for if an admin logs in and is an admin of more than one group? I'd expect most content designers in a council will be admins on many of the groups/microsites
2. The render array you are proposing looks like a good idea to me.

**Comment by ekes** [comment]
So far the understanding is that a user who is to edit content logs into the microsite url. So there is only one group, the one for that microsite hostname. The menu displayed are the local tasks for the group based on the hostname. If they want to edit another one they need to log into that microsite. 

On the control site it is possible to enter content, from within the group context, but it's been built round the controller so far.

**Comment by markconroy** [comment]
That makes sense, but I'd presume since this is for councils that most editors will be editors on more than one site and would expect to login just once to their microsites portal. 

If the original thought was that this was going to be part of LGD rather than a separate instance, they'd be managing all their content from within their LGD site

**Comment by finnlewis** [comment]
Interesting assumption @markconroy - I had assumed the opposite, that they would want to log into the site they are managing to keep it all in context. 

We should add these competing assumptions to the assumptions log and ultimately confirm if it is one or the other, or both! 

Meanwhile, does this assumption have a material impact on how the localised group menu works @ekes ?

**Comment by finnlewis** [comment]
Either way, we will need to style the block.

If I place the 'Microsite tasks' block in the 'tabs' region, then log into Microsite 1 as admin1, it looks like this: 

(you can just see the links against the dark background)

![Image](https://user-images.githubusercontent.com/326588/169474327-eaba5458-902a-4e4b-822f-8aefdf509872.png)

@msayoung one for you?

**Comment by ekes** [comment]
> Meanwhile, does this assumption have a material impact on how the localised group menu works @ekes ?

When you are on the group domain you have the group menu everywhere.
When you are on the control site you have the group menu when you are in the group.
 
The point raised on slack, but not here yet I think, by mark was that with the desire to make all of the group remain in the admin theme consistently, it means on the control site you never see the theme for the microsite. So should anyone be editing the theme, or want to see a preview of the content in the theme, on the control site it's presently not possible. They can see the content, but in the control site theme. There is a note about this on the PR that set the admin theme.

**Comment by ekes** [comment]
Can we close this one? Anything new in a new issue? This is merged?

**Comment by markconroy** [comment]
I think this is good to close now. There's a separate ticket for theming those tabs.
