### ISSUE TITLE
Remove /admin/microsites from microsite

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#38]
- [ ] Remove microsites admin list from microsite
- [x] ~~Error on microsites admin if accessed from a microsite.~~
```
Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Microsites[localgov_microsites_overview]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base_table.id' in 'where clause': SELECT "groups_field_data"."id" AS "id" FROM "groups_field_data" "groups_field_data" WHERE (("groups_field_data"."status" = :db_condition_placeholder_0) AND ("groups_field_data"."type" IN (:db_condition_placeholder_1))) AND ("base_table"."id" = :db_condition_placeholder_2) LIMIT 51 OFFSET 0; Array ( [:db_condition_placeholder_0] => 1 [:db_condition_placeholder_1] => microsite [:db_condition_placeholder_2] => 1 ) in main() (line 19 of index.php). 
```

**Comment by ekes** [comment]
The other is hopefully fixed, without breaking anything else (tests still passing) on domain_group
https://git.drupalcode.org/sandbox/ekes-3278349/-/commit/82875634727eb11f404c616932bbb0d7e080f5aa

That you shouldn't be able to access it on a microsite is surprisingly more complicated. The view access on domain requires knowing the domain hostname; there isn't an access filter for 'default' 'not default' domain. So I guess to remove this we'll have to write one.

Updating the issue title for this issue.

**Comment by finnlewis** [comment]
I think this fixed @ekes , no?
