### ISSUE TITLE
Saving "Site settings" is resetting theme override

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_microsites_group#382]
## How to reproduce
0. Create a microsite as a user with the microsite-controller role.
0.5.  Login to the new microsite.
1. Override the microsite theme from the "Site settings > Theme override" tab.  Note down the newly selected microsite theme name.
2. Edit the site name or site slogan from the "Site settings > Site settings" tab.  Save the form.
3. Reopen the "Site settings > Theme override" tab and compare the selected theme with the one noted down in step 1.  These will defer.

Copying @clearspotmedia @ekes @finnlewis

**Comment by finnlewis** [comment]
Thanks @Adnan-cds 

I can confirm this behaviour locally. 

Have @ekes or @stephen-cox got any time to look at this? If not, just let me know and I can take a look later.

**Comment by ekes** [comment]
Am I missing something here, but I can't reproduce it. I've made a microsite controller, logged in on the control site, made a microsite, then overriden the theme, then changed the name and slogan, but the theme is still the same overriden value.
[using localgov microsites group at d6f06951 and domain_group at 949a60b]

**Comment by Adnan-cds** [comment]
Sorry Ekes, forgot to mention that you need to try this while logged into the microsite.  I have updated the [reproduction steps](https://github.com/localgovdrupal/localgov_microsites_group/issues/382#issue-1526008517) above.

**Comment by ekes** [comment]
Think https://github.com/localgovdrupal/localgov_microsites_group/pull/383 should fix it for you?
