### ISSUE TITLE
"Generate automatic url alias box" is always checked when opened for editing

### ISSUE THREAD

**Issue by bobbulman** [localgovdrupal/localgov_microsites_group#408]
Problem: 
Custom path is being overwritten when doing successive edits. The only way to preserve a custom path on a page is to keep un-checking "Generate automatic url alias box" every time an edit is done.

Steps to recreate the issue:
Open a page for editing
Un-check the "Generate automatic url alias box" and enter a custom path
Save the page
Re-open the page again for editing
Observe the "Generate automatic url alias box" is ticked again
Save the page
Re-open the page again for editing
Observe the custom path has now been overwritten with the default value

**Comment by markconroy** [comment]
Thanks Bob. That's an interesting one. I'm moving this issue from localgov_microsites_base to localgov_microsites_group repo as it's not an issue with the theme, rather it's with the configuration/backend code.

**Comment by stephen-cox** [comment]
Thanks for reporting @bobbulman There's a potential fix for this here: https://github.com/localgovdrupal/localgov_microsites_group/pull/411
