### ISSUE TITLE
Drupal 10 permissions

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#415]
Coming from https://github.com/localgovdrupal/localgov_microsites/issues/347

When testing a Drupal 10 install, I get this: 

> Adding non-existent permissions to a role is not allowed. The incorrect permissions are "assign microsites_controller role", "assign microsites_trusted_editor role", "bypass group access", "edit layout paragraphs plugin config". 

So we need to sort out the permissions to ensure we've got the right ones.

CC @stephen-cox

**Comment by stephen-cox** [comment]
Should be fixed with https://github.com/localgovdrupal/localgov_microsites_group/pull/414/commits/5f1fc12a44046210ac7c0b0a2ee6d49c35e7eb64
