### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by richard-s-rowley** [localgovdrupal/localgov_microsites_group#42]

**Comment by richard-s-rowley** [comment]
Hi Mark, Maria,

I have come up with a list of 21 fonts we could offer at the start. Of these, all 21 are suitable for headings and 17 for body text.

I wanted to cater for a whole variety of vibes (including attractions and services aimed at children). The sans fonts are half gothics and half humanists, and go from neutral to more characterful. If you think this is too many to go with at the start, I can definitely trim. You can see them on the [Miro board](https://miro.com/app/board/uXjVOStMNW8=/?moveToWidget=3458764524625161432&cot=14).

We need a bold, a regular and an italics of each of these. The headings don't need italics. I don't think we need a 'bold italic'. 

If you're looking for a default font, I suggest Public Sans.

Let me know what you think / if you'd like to discuss!

**Sans**
Roboto
Public sans
IBM Plex Sans
Barlow
Work sans
Open sans
Cabin
PT Sans
Alegreya sans
Junction

**Serif**
Source Serif Pro
Vollkorn
Libre Baskerville
Merriweather
PT serif

**Slab serif**
Arvo

**Monospace**
Space mono

**Headings only**
Archivo Black
Archivo Narrow
Sporting Grotesk
Playfair Display

**Comment by richard-s-rowley** [comment]
I can also provide links to the files or the files themselves if that helps.

**Comment by markconroy** [comment]
This is great work Richard. Thanks very much. 

Are these all available as Google Fonts?

**Comment by markconroy** [comment]
Gonna start working on this now.

**Comment by richard-s-rowley** [comment]
Hey Mark,
They are all on Google fonts, except:
https://www.theleagueofmoveabletype.com/junction
https://velvetyne.fr/fonts/sporting-grotesque/

They are two of my quirkier favourites but I can provide Google alternatives if that helps.

**Comment by markconroy** [comment]
I have all the others ones, I'll grab those ones tomorrow.

**Comment by finnlewis** [comment]
What's left to do on this one?

**Comment by markconroy** [comment]
There's a PR for this. Once merged, this should be complete (unless we want to make the form prettier).
