### ISSUE TITLE
Set if particular content types can be created in different Microsites

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites_group#428]
>  I'll be honest here. My temptation is now to remove group_permissions and use custom entity access to set if content can be created - it will then always be possible to be viewed if it has been created.

_Originally posted by @ekes in https://github.com/localgovdrupal/localgov_microsites_group/issues/427#issuecomment-1772527308_

**Comment by finnlewis** [comment]
Good idea. I wonder how much time this would take?

If we can estimate the size of the job and upgrade paths, we can assess.

**Comment by ekes** [comment]
Well the migration to a field, supplied with modules, and a new hook... straightforward. I've done a fair bit when prodding.

However I am reminded why going for group_permissions in the first place was more 'straightforward'. As the group routes to create content, and probably other custom /group/{group}/... routes, use the plugin access which doesn't look at the entity_access hooks at all.

So we'd do entity access hooks _and_ add additional access checks on specific routes _or_ decorate the access service plugin further -- thinking about it the later might be best. But, it'd probably still be better for performance rather than entering the calculator on a per-group basis as group_permissions does, and it'd be 'simpler'. So probably still worth it for what we need which is the _impression_ of particular content types per site and _simple_ _ui_ without the additional types.

**Comment by ekes** [comment]
- [x] Switch to use entity access checks per group.
 - [ ] Optional: see if this can be better done with a permissions service per group domain context
 - [ ] Add more tests to ensure this is working correctly.

**Comment by finnlewis** [comment]
Added this issue to write some tests: https://github.com/localgovdrupal/localgov_microsites_group/issues/464

**Comment by ekes** [comment]
>  Optional: see if this can be better done with a permissions service per group domain context

https://github.com/localgovdrupal/localgov_microsites_group/pull/470

> Add more tests to ensure this is working correctly.

https://github.com/localgovdrupal/localgov_microsites_group/pull/469

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/470 has been merged and released.

I think this can be closed, thanks @ekes !
