### ISSUE TITLE
URL aliases available for all microsites on a given piece of content

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#509]
For example: 
![image](https://github.com/user-attachments/assets/dd6df611-4fe0-47a3-9aae-71972ff180da)

@stephen-cox recalls writing some code to fix this... maybe we need to fond that and update it?

**Comment by stephen-cox** [comment]
This is strange ... I'm sure I did something to fix this a while ago, but I can't see any sign of it :shrug: 

PR #510 adds some code to fix it.
