### ISSUE TITLE
Currently using Missing or invalid modules: variationcache

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites_group#513]
After upgrading to Group 3.3.0 I see the following error:

The following modules are marked as installed in the core.extension configuration, but they are missing: 

 * variationcache

Group dropped the requirement for this with https://git.drupalcode.org/project/group/-/commit/4349a9f1c0779db024b5657145f139bb5db213bf and the module is deprecated as the functionality was included in Drupal 10.2: https://www.drupal.org/project/variationcache

I suggest we add a requirement for variation cache to our composer.json, but include an update hook to uninstall the module. We can then drop the requirement for this module with a later release.

Unless anyone has a better way to deal with this?

**Comment by ekes** [comment]
Or the other way round, change localgov_microsites_group to have a version max 3.2 and in that also uninstall variationcache; and then make the next release 3.3+

**Comment by stephen-cox** [comment]
Here's a PR doing it my way round https://github.com/localgovdrupal/localgov_microsites_group/pull/514, but happy to change it if people prefer to pin Group to 3.2 for now

**Comment by ekes** [comment]
It's safer your way round.
