### ISSUE TITLE
Domain Specific Paths (aliases) don't work

### ISSUE THREAD

**Issue by chriswales95** [localgovdrupal/localgov_microsites_group#517]
Hi all,

Apologies if this is not the correct place for this issue (if that is the case, transfer it). I think it is because there's some other issues related to aliases etc in this repo but that's besides the point.

There seems to be a big problem with domain specific paths at the moment. If you enter one, it doesn't work. It gets generated from the page title -- no matter what you put in the alias box.

This may be an issue with the domain_path module but I'm not quite sure.

# How to replicate

1. Install LGD Microsites
2. Create a microsite
3. Create some content
4. Edit the domain specific path / alias
5. Save content
6. It shouldn't save the alias. It should be generated from the title

# Video of issue
https://www.loom.com/share/14ccbc443a7e4f0499b7d1fd30be4220?sid=d515b2c0-90b5-447e-b59f-05603f0f84c0

**Comment by stephen-cox** [comment]
@chriswales95 There are a couple of issues with Domain Paths that need looking at. They are issues we had previously fixed but have re-occurred. I think this one was originally solved with #338, but is happening again

**Comment by chriswales95** [comment]
Hi @stephen-cox, thanks for confirming. I didn't know it was a regression but that makes sense.

**Comment by finnlewis** [comment]
Hi @chriswales95 

This should be fixed in the latest release. 

@stephen-cox has also added some tests in  https://github.com/localgovdrupal/localgov_microsites_group/pull/533/files

So hopefully this wont regress again! 

Thanks both for your collaboration on this one.

:)
