### ISSUE TITLE
Failing tests in localgov_microsites_group since 19th October

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#518]
> Looks like the failed tests here and other PRs mentioned today are unrelated as we get them on the main project from this morning's run https://github.com/localgovdrupal/localgov_microsites_project/actions/runs/11454313013/job/31868361713 looks like something needs updating in the `group_sites` module.
> 
> Looks to have started on this run (19th Oct) https://github.com/localgovdrupal/localgov_microsites_project/actions/runs/11415200204

_Originally posted by @millnut in https://github.com/localgovdrupal/localgov_microsites_group/issues/510#issuecomment-2429416236_

**Comment by finnlewis** [comment]
![image](https://github.com/user-attachments/assets/2f824dc1-dacc-4e97-864e-faa55b9ae27d)

Possibly related to the release of group 3.3.0 ?

**Comment by millnut** [comment]
@finnlewis also see https://github.com/localgovdrupal/localgov_microsites_group/issues/511 where I did a very minimal investigation at the time

**Comment by finnlewis** [comment]
Thanks @millnut ! Closing this as a dupe!
