### ISSUE TITLE
Remove Heading 1 from the wysiwyg, and add a page title? (question)

### ISSUE THREAD

**Issue by richard-s-rowley** [localgovdrupal/localgov_microsites_group#63]

**Comment by richard-s-rowley** [comment]
Is there a reason we don't have a page title on the page?
As it is someone can add multiple ```<h1>```s

**Comment by msayoung** [comment]
PR https://github.com/localgovdrupal/localgov_microsites/pull/99 removes the H1 in the wysiwyg

I think we are now printing the page title but it hasn't made it to the demo site
