### ISSUE TITLE
Dragging paragraph to new section initially moves it to 'disabled paragraphs' section. You need to move-save-move-save.

### ISSUE THREAD

**Issue by richard-s-rowley** [localgovdrupal/localgov_microsites_group#64]

**Comment by finnlewis** [comment]
I think this works much better in v 2.x

**Comment by stephen-cox** [comment]
@richard-s-rowley  I'm unable to reproduce this. Moving paragraphs between sections works fine for me.

Are you able to give steps on how to reproduce this?

**Comment by richard-s-rowley** [comment]
Also works fine for me now @stephen-cox so I will close and raise a separate ticket if I see it again
