### ISSUE TITLE
show the Tours automatically to people on their first visit

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#82]

**Comment by stephen-cox** [comment]
@msayoung @finnlewis It seems that there's not a keen interest in having Tour autoplay to people when they first visit a page: https://www.drupal.org/project/drupal/issues/2934417

The agreed autoplay method is to add `?tour=1` to the end of the URL. For example: https://microsites.localgovdrupal.org/admin/microsites?tour=1

I'm sure we could get the tours to autoplay when first visiting the page, but the code won't be trivial as we'll need to set a cookie to ensure it only plays once.

Can we use the `?tour=1` somehow when getting people to visit pages for the first time?

As it stands the controller user doesn't have permissions to use Tour. This PR #86 fixes this and some other issues I found while looking into this.

**Comment by finnlewis** [comment]
Still a live one?
