### ISSUE TITLE
White space in the admin form

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#87]
Seem to have a big white space at the top of the tabs. I think they are new ?

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/170248313-70c56853-d996-47e3-b3d4-ce53a22b482d.png)

**Comment by finnlewis** [comment]
I can't figure out what is going on here @msayoung / @markconroy - any ideas? Something to do with Gin and / or Claro?

**Comment by msayoung** [comment]
![image](https://user-images.githubusercontent.com/3852805/170286266-148f02d9-7565-4809-a61d-e581dcb9def9.png)

seems to be Claro

**Comment by finnlewis** [comment]
When did this start? I'm sure it wasn't there yesterday

**Comment by finnlewis** [comment]
Is there a quick fix we can do to resolve this?

**Comment by finnlewis** [comment]
@markconroy and @markconroy  and @finnlewis realised this is due to the latest release of Gin theme.

New issue created here: https://www.drupal.org/project/gin/issues/3282294

**Comment by msayoung** [comment]
hunted this down to a bug introduced in beta3 of Gin . have pinned Gin at beta2 for testing

**Comment by finnlewis** [comment]
Looks like Sascha found the problem: https://www.drupal.org/project/gin/issues/3282294#comment-14536806

**Comment by finnlewis** [comment]
Sascha would love some more eyes on the CSS changes, either @markconroy or @msayoung able to take a look and comment? 

https://www.drupal.org/project/gin/issues/3282294#comment-14536806

Here's the diff: 

https://git.drupalcode.org/project/gin/-/merge_requests/148/diffs

It works for me, but I've not understood why yet!

**Comment by markconroy** [comment]
I think I found the issue 
https://www.drupal.org/project/gin/issues/3282294#comment-14537391
