### ISSUE TITLE
Remove Heading 1 text from default content

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#88]
We removed the Heading 1 from the WYSIWYG so the text that now reads "Heading 1" needs to be removed

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/170248700-6cdcfda3-b49a-4ef6-ae60-2c5f8e2c003b.png)

**Comment by finnlewis** [comment]
You mentioned this earlier @msayoung  - are you working on it?

**Comment by msayoung** [comment]
I did it actually - there's a PR somewhere

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites/pull/110

**Comment by finnlewis** [comment]
Brill - merge away!
