### ISSUE TITLE
Clear node group content cache when saving a group

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#94]
When adding footer blocks (on council test sites) they can't be seen immediately. They turn up after a while, or after a cache clear

**Comment by finnlewis** [comment]
Could we add a brute force cache clear on saving group config or new nodes?

**Comment by stephen-cox** [comment]
I have added a hook to invalidate the node cache when a group is saved with #95 

https://github.com/localgovdrupal/localgov_microsites_group/blob/9b4b6df511cb6ca5a8f8b2491ed580568a4f0aa2/localgov_microsites_group.module#L81

The problem with this approach is invalidates all nodes when we only want those associated with the group. Invalidating tags like `group:$id` didn't work. 

One approach would be to add a cache tag to all group content so we can selectively clear stuff as required on a group basis.

**Comment by finnlewis** [comment]
@stephen-cox do we want to close this for now or keep it open to refactor with more targeted cache tags?

**Comment by finnlewis** [comment]
We need to address this, after resolving Group Context issue.
