### ISSUE TITLE
Add new content bug

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#98]
As a microsite admin
If a add a new piece of content, then save
I am presented with a blank screen (with two buttons)

I think this should offer the ability to add a URL alias

Perhaps a ramification of hiding the Menu options @stephen-cox

**Comment by finnlewis** [comment]
@markconroy thinks this might be a matter of enabling the '2 step wizard'.
@stephen-cox mentions path aliases

**Comment by markconroy** [comment]
![Image](https://user-images.githubusercontent.com/2183332/172606731-77f02c51-8f8e-470c-8fa9-7dbe80eec989.jpg)

If we turn off the "2 step wizard" feature here, we don't get the extra screen (however, we'll need this (I think) if we want fields here to set URLs for example).

**Comment by msayoung** [comment]
Closing, no longer an issue
